global using Microsoft.EntityFrameworkCore;
global using DotnetHeadStart.Models;
global using Serilog;
global using ILogger = Serilog.ILogger;
global using Microsoft.Extensions.Configuration;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.AspNetCore.Mvc;
global using System.Diagnostics;
global using DotnetHeadStart.MVC.Data;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.OpenApi;