global using System.Diagnostics;
global using DotnetHeadStart.MVC.Data;
global using DotnetHeadStart.MVC.Models;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using ILogger = Serilog.ILogger;
global using DotnetHeadStart;