global using System.ComponentModel.DataAnnotations;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Builder;
global using ILogger = Serilog.ILogger;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Serilog;
global using MimeKit;
global using MimeKit.Text;
global using MailKit.Net.Smtp;
global using System.Linq.Expressions;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using DotnetHeadStart.QueryFilters;
global using System.Diagnostics.CodeAnalysis;