global using System.ComponentModel.DataAnnotations;
global using Microsoft.EntityFrameworkCore;
global using DotnetHeadStart.DB;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Builder;
global using ILogger = Serilog.ILogger;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Serilog;
